version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.dbs
    ports:
      - "8002:8002"
    networks:
      - backend

  business:
    build:
      context: .
      dockerfile: Dockerfile.bs
    ports:
      - "8001:8001"
    networks:
      - backend

  client:
    build:
      context: .
      dockerfile: Dockerfile.cs
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
      - business

networks:
  backend: